---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-provisioner-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hostpath-provisioner-operator
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - list
      - get
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner-operator
subjects:
  - kind: ServiceAccount
    name: hostpath-provisioner-operator
    namespace: hostpath-provisioner
roleRef:
  kind: ClusterRole
  name: hostpath-provisioner-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hostpath-provisioner-operator
subjects:
  - kind: ServiceAccount
    name: hostpath-provisioner-operator
    namespace: hostpath-provisioner
roleRef:
  kind: Role
  name: hostpath-provisioner-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hostpath-provisioner-operator
  template:
    metadata:
      labels:
        name: hostpath-provisioner-operator
    spec:
      serviceAccountName: hostpath-provisioner-operator
      containers:
        - name: hostpath-provisioner-operator
          # Replace this with the built image name
          image: quay.io/kubevirt/hostpath-provisioner-operator:v0.9.0
          command:
            - hostpath-provisioner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hostpath-provisioner-operator"
            - name: PROVISIONER_IMAGE
              value: "quay.io/kubevirt/hostpath-provisioner:v0.9.0"
