user:
  name: kc2user
  credentials:
    password: 'kc2user'
    sshpubkeysecretpassword: 'kc2user'
    sshpubkeysecret: 'kargo-sshpubkey-kc2user'
    sshpubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB/zPcAdyHRElufWDNQ1mZUWp4V9jDmaWX35ApsXgxfMHBuz3n8VLGVJuXodAAxeRbbE7Rws8BQcCH4DAMKKLHYZRdJtk3ZUw7rm0i/aq0wkeld7Yp6H/fv1ud3mudp7/+3fQ3gV8RmAO8+FS4jNBMciqtY6mWThKciwnkBWmH5atl6GsZ1ZQ+Y8+W4hXnaF6UEU1+xZ8ja+hu81a9fhejcV+m3RwT511kW5IXDe6wkq9tsIEC529VGI7XuySYvusbchivWYxmE+TBMmId3voGCfkl8hIemUG3/LvQWeK95B/6vBKDCFlmABn60zxrjPkdknWPbu4zg+VJWnslX+rDqSe2cBpHqQ8yDxegPcmXNKv2Qp0h8HhEljWoLc4U5x4hlceDraWBehj8i4N6p+Yt678+jUpOCwGC8z9l+zUrG6NPvbHZ2aIBC3eUteYPtmScNLvOiFASPo/9GQQDNqZclQZf5QGDToAV2rV1B4jJPV8fv/1rlgen6O1PNitKo9FlUfr0WA1IXev6CiJUt4x210BzhTlD84S2A0gHJRbeVVkjWKMx/vo/wqEKTg/vvzSOhFDDlKUxSsguL5rrtOxdGj4sUtjeVRuDjwk1u1DH8P75rI0R/1QaeDixJbRi8Q1315z+MrvJuvzJpMTieldqffNUnexMZcFox8yI8KlVt2U="

network:
  vlan_id: 101
  subnet_mask: 24
  host_interface: br0
  primary: kargo-net-attach-def-br0
  search: kubespray.home.arpa
  metallb:
    ingress1:
      ipv4: 192.168.16.66
  vrrp:
    ipv4: 192.168.1.60
  vyos:
    eth1:
      ipv4: "192.168.16.1"
    dns1: 192.168.1.1
    dns2: 8.8.8.8
  bastion:
    dns: 192.168.16.1
    gateway: 192.168.16.1
    ipv4: "192.168.16.12"
  node1:
    dns: 192.168.16.1
    gateway: 192.168.16.1
    ipv4: "192.168.16.61"
  node2:
    dns: 192.168.16.1
    gateway: 192.168.16.1
    ipv4: "192.168.16.62"
  node3:
    dns: 192.168.16.1
    gateway: 192.168.16.1
    ipv4: "192.168.16.63"

nodes:
  pullPolicy: IfNotPresent
  # VPC NAT Gateway & Firewall
  vyos:
    annotations: {}
    cpu:
      cores: 2
      model: host-passthrough
    memory: 512M
    source:
      tag: "1.4-rolling"
      image: "quay.io/containercraft/vyos"
  # VPC Bastion with SSH & RDP Access
  bastion:
    annotations: {}
    cpu:
      cores: 8
      model: host-passthrough
    memory: 8G
    source:
      image: "docker.io/containercraft/ubuntu"
      tag: "21.10"
    storage:
      vda:
        size: "64G"
        class: "hostpath-provisioner"
        accessModes: ReadWriteOnce
        volumeMode: Block
  # Kubespray master nodes
  masters:
    annotations: {}
    cpu:
      cores: 6
      model: host-passthrough
    memory: 16G
    source:
      image: docker.io/containercraft/fedora
      tag: 35
    storage:
      vda:
        size: "64G"
        class: "hostpath-provisioner"
        accessModes: ReadWriteOnce
        volumeMode: Block
      vdb:
        size: "8G"
        class: "hostpath-provisioner"
        accessModes: ReadWriteOnce
        volumeMode: Block
      vdc:
        size: "64G"
        class: "hostpath-provisioner"
        accessModes: ReadWriteOnce
        volumeMode: Block
      vdd:
        size: "64G"
        class: "hostpath-provisioner"
        accessModes: ReadWriteOnce
        volumeMode: Block

replicaCount: 1
imagePullSecrets: []
affinity: {}
tolerations: []
nodeSelector: {}
podAnnotations: {}
securityContext: {}
serviceAccount:
  create: false
  annotations: {}
  name: "tenant"
nameOverride: ""
