{{- $sshPubKey := "kargo-vpc.sshpubkey" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "user1-kargo-sshpubkey") }}
{{- if $secret }}
{{- $sshPubKey = index $secret.data "sshpubkey" }}
{{- end -}}
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: bastion-{{ include "kargo-vpc.fullname" . }}
  labels:
    app: bastion
    kubevirt.io/os: linux
    vpc: {{ include "kargo-vpc.fullname" . }}
    qubo.containercraft.io/project: "kargo-vpc"
    userdata/sum: {{ include (print $.Template.BasePath "/cloudinit.yaml") . | sha256sum | trunc 63 }}
    {{- include "kargo-vpc.labels" . | nindent 4 }}
spec:
  running: true
  template:
    metadata:
      labels:
        app: vyos
        kubevirt.io/os: linux
        vyos.io/release: "1.4-rolling"
        vpc: {{ include "kargo-vpc.fullname" . }}
        qubo.containercraft.io/project: "kargo-vpc"
        userdata/sum: {{ include (print $.Template.BasePath "/cloudinit.yaml") . | sha256sum | trunc 63 }}
        {{- include "kargo-vpc.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: {{ .Values.bastion.cpu.cores }}
          model: {{ .Values.bastion.cpu.model }}
          dedicatedCpuPlacement: false
          threads: 1
          sockets: 1
        machine:
          type: "pc-q35-rhel8.3.0"
        resources:
          {{- toYaml .Values.bastion.resources | nindent 10 }}
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
          - name: bastion-disk-vda-root
            bootOrder: 1
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: enp1s0
            model: virtio
            bootOrder: 2
            bridge: {}
      hostname: bastion-{{ include "kargo-vpc.fullname" . }}
      networks:
      - name: enp1s0
        multus:
          networkName: {{ include "kargo-vpc.fullname" . }}.brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}
      volumes:
      - name: bastion-disk-vda-root
        containerDisk:
          image: "{{ .Values.bastion.image.repository }}:{{ .Values.bastion.image.tag }}"
          imagePullPolicy: {{ .Values.bastion.image.pullPolicy }}
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                dhcp6: false
                addresses:
                  - 192.168.16.12/24
                gateway4: 192.168.16.1
                nameservers:
                  addresses:
                  - 192.168.16.1
                  search:
                  - dmz.home.arpa
          userData: |
            #cloud-config
            ssh_pwauth: true
            chpasswd:
              list: |
                 ubuntu:ubuntu
              expire: False
            users:
              - default
              - name: ubuntu
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo
                shell: /bin/bash
                ssh-authorized-keys:
                  - {{ .Values.bastion.credentials.sshpubkey }}
            hostname: bastion-{{ include "kargo-vpc.fullname" . }}
            runcmd:
              - "systemctl enable --now sshd"
              - "apt-get update"
              - "apt-get install --install-recommends -y xrdp gnome-tweak-tool ubuntu-desktop"
              - "mkdir -p /home/ubuntu/.kube"
              - "chown -R ubuntu:ubuntu /home/ubuntu"
              - "usermod -a -G xrdp ubuntu"
              - "usermod -a -G ssl-cert ubuntu"
              - "apt-get -y upgrade"
