apiVersion: apps/v1
kind: Deployment
metadata:
  name: konductor
  labels:
    app: konductor
    app.kubernetes.io/name: konductor
    {{- include "konductor.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "konductor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "konductor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "konductor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostname: {{ include "konductor.fullname" .  }}
      volumes:
      - name: dot-local
        persistentVolumeClaim:
          claimName: konductor-pvc-local
      - name: home-platform
        persistentVolumeClaim:
          claimName: konductor-pvc-platform
      - name: dot-ssh
        persistentVolumeClaim:
          claimName: konductor-pvc-ssh
      - name: dot-gitconfig
        persistentVolumeClaim:
          claimName: konductor-pvc-gitconfig
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: home-platform
            mountPath: /root/platform
          - name: dot-local
            mountPath: /root/.local
          - name: dot-ssh
            mountPath: /root/.ssh
          - name: dot-gitconfig
            mountPath: /root/.gitconfig
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
