apiVersion: v1
kind: Service
metadata:
  name: {{ include "konductor.fullname" . }}-code
  namespace: konductor
  labels:
    {{- include "konductor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "konductor.selectorLabels" . | nindent 4 }}
