apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vyos-gateway
  namespace: kargo
  labels:
    app: vyos
    kubevirt.io/os: linux
    vyos.io/release: "1.4-rolling"
    containercraft.io/project: "qubo/library/kargo-vpc"
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: vyos-volume-vda-root
      annotations:
        kubevirt.io/provisionOnNode: "node1"
    spec:
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 8G
        storageClassName: ceph-filesystem
      source:
        registry:
          url: "docker://quay.io/containercraft/vyos:1.4-rolling"
          imagePullPolicy: Always
  template:
    metadata:
      labels:
        app: vyos
        kubevirt.io/os: linux
        vyos.io/release: "1.4-rolling"
        containercraft.io/project: "qubo/library/kargo-vpc"
    spec:
      nodeSelector:
        node-role.kubernetes.io/kubevirt: ""
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 2
          threads: 1
          sockets: 1
          model: host-passthrough
          dedicatedCpuPlacement: false
        machine:
          type: pc-q35-rhel8.3.0
        resources:
          requests:
            memory: 1G
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: false
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
          - name: vyos-disk-vda-root
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
              readonly: true
          interfaces:
          - name: eth0
            model: virtio
            bridge: {}
          - name: eth1
            model: virtio
            bridge: {}
      networks:
      - name: eth0
        multus:
          networkName: kargo-net-attach-def-br0
      - name: eth1
        multus:
          networkName: kargo-net-attach-def-br0-vlan100
      volumes:
      - name: vyos-disk-vda-root
        dataVolume:
          name: vyos-volume-vda-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: vyos-cloudconfig
