{{- $sshPubKey := "kubespray.sshpubkey" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "user1-kargo-sshpubkey") }}
{{- if $secret }}
{{- $sshPubKey = index $secret.data "sshpubkey" }}
{{- end -}}
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: bastion-{{ include "kubespray.fullname" . }}
  labels:
    app: bastion
    kubevirt.io/os: linux
    vpc: {{ include "kubespray.fullname" . }}
    qubo.containercraft.io/project: "kubespray"
    {{- include "kubespray.labels" . | nindent 4 }}
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: bastion-volume-vda-root
      annotations:
        kubevirt.io/provisionOnNode: node4
      labels:
        app: kubespray
    spec:
      source:
        registry:
          url: "docker://{{ .Values.bastion.image.repository }}:{{ .Values.bastion.image.tag }}"
          imagePullPolicy: IfNotPresent
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 64G
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64G
        storageClassName: hostpath-provisioner
      persistentVolumeReclaimPolicy: Delete
      storageClassName: hostpath-provisioner
      volumeMode: Block
  template:
    spec:
      evictionStrategy: LiveMigrate
      nodeSelector:
        kargo-zone.containercraft.io/d: ""
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          model: {{ .Values.bastion.cpu.model }}
          threads: {{ .Values.bastion.cpu.cores }}
          dedicatedCpuPlacement: false
          sockets: 1
          cores: 1
        resources:
          {{- toYaml .Values.bastion.resources | nindent 10 }}
        machine:
          type: "pc-q35-rhel8.3.0"
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
          - name: bastion-disk-vda-root
            bootOrder: 1
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: enp1s0
            model: virtio
            bootOrder: 2
            bridge: {}
      hostname: bastion-{{ include "kubespray.fullname" . }}
      networks:
      - name: enp1s0
        multus:
          networkName: {{ include "kubespray.fullname" . }}.brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: bastion-disk-vda-root
        dataVolume:
          name: bastion-volume-vda-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                dhcp6: false
                addresses:
                  - 192.168.16.12/24
                gateway4: 192.168.16.1
                nameservers:
                  addresses:
                  - 192.168.16.1
                  search:
                  - kubespray.home.arpa
          userData: |
            #cloud-config
            ssh_pwauth: true
            chpasswd:
              list: |
                 {{ .Values.user.name }}:{{ .Values.user.credentials.pass }}
              expire: False
            users:
              - name: {{ .Values.user.name }}
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo,lxd,docker
                shell: /bin/bash
                ssh-authorized-keys:
                  - {{ .Values.user.credentials.sshpubkey }}
            hostname: bastion-{{ include "kubespray.fullname" . }}
            runcmd:
              - "systemctl enable --now sshd"
              - "mkdir -p /home/{{ .Values.user.name }}/.kube"
              - "chown -R {{ .Values.user.name }}:{{ .Values.user.name }} /home/{{ .Values.user.name }}"
              - "usermod -a -G xrdp {{ .Values.user.name }}"
              - "usermod -a -G ssl-cert {{ .Values.user.name }}"
              - "curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz | tar xzvf - --directory /usr/local/bin oc kubectl"
              - "curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xzvf - --directory /usr/local/bin openshift-install"
              - "apt-get update"
              - "apt-get -y upgrade"
              - "apt-get install --install-recommends -y jq xrdp gnome-tweak-tool {{ .Values.user.name }}-desktop docker.io apache2-utils libvirt-clients"
