apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: '{{ include "kubespray.fullname" . }}.brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}'
  labels:
    qubo.containercraft.io/project: "kubespray"
    containercraft.io/project: qubo
    vpc: {{ include "kubespray.fullname" . }}
spec:
  config: |
      {
          "cniVersion": "0.3.1",
          "name": "brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}",
          "plugins": [
              {
                  "type": "bridge",
                  "bridge": "brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}",
                  "ipam": {}
              },
              {
                  "type": "tuning"
              }
          ]
      }
