#cloud-config
disable_root: true
ssh_pwauth: true
write_files:
- encoding: b64
  content: {{ tpl (.Files.Get "userdata/dnf.conf") . | b64enc }}
  path: /etc/dnf/dnf.conf
  permissions: '0644'
  owner: root:root
chpasswd:
  expire: False
  list: |
     {{ .Values.user.name }}:{{ .Values.user.credentials.password }}
users:
  - name: {{ .Values.user.name }}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: wheel
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - {{ .Values.user.credentials.sshpubkey }}
growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: true
device_aliases: {'etcd': '/dev/vdb'}
disk_setup:
  /dev/vdb:
    table_type: gpt
    layout: True
    overwrite: True
fs_setup:
  - label: etcd
    device: '/dev/vdb'
    partition: 'auto'
    filesystem: 'ext4'
mounts:
 - [ vdb, /var/lib/etcd, "ext4", "defaults", "1", "1"  ]
final_message: "The system is up after $UPTIME seconds"
package_upgrade: false
runcmd:
  - "setenforce 0"
  - "grubby --update-kernel ALL --args selinux=0"
  - "nmcli con modify 'Bridge br0' ethernet.cloned-mac-address random"
  - "systemctl restart NetworkManager"
power_state:
  mode: reboot
  delay: "now"
  timeout: 60
  condition: True
  message: "Going down for a reboot"
