version: 2
ethernets:
  eth0:
    dhcp4: false
    dhcp6: false
bridges:
  br0:
    dhcp4: false
    dhcp6: false
    addresses:
      - {{ .Values.network.node2.ipv4 }}
    gateway4: {{ .Values.network.node2.ipv4 }}
    interfaces:
      - eth0
    nameservers:
      search:
        - {{ .Values.network.search }}
      addresses:
        - {{ .Values.network.node2.dns }}
    macaddress: "02:d2:76:00:00:20"
