version: 2
ethernets:
  eth0:
    dhcp4: false
    dhcp6: false
bridges:
  br0:
    max-age: 0
    ageing-time: 0
    dhcp4: false
    dhcp6: false
    addresses:
      - {{ .Values.network.node1.ipv4 }}
    gateway4: {{ .Values.network.vyos.eth1.ipv4 }}
    interfaces:
      - eth0
    nameservers:
      search:
        - {{ .Values.network.search }}
      addresses:
        - {{ .Values.network.node1.dns }}
#   macaddress: "02:d1:76:00:00:20"
