#cloud-config
write_files:
- encoding: b64
  content: {{ tpl (.Files.Get "userdata/haproxy.cfg") . | b64enc }}
  owner: root:root
  path: /etc/haproxy/haproxy.cfg
  permissions: '0644'
ssh_authorized_keys:
  - {{ .Values.user.credentials.sshpubkey }}
vyos_config_commands:
  - mkdir -p /etc/haproxy
  - configure
  - set firewall all-ping 'enable'
  - set firewall syn-cookies 'enable'
  - set firewall config-trap 'disable'
  - set firewall log-martians 'enable'
  - set firewall ip-src-route 'disable'
  - set firewall send-redirects 'enable'
  - set firewall broadcast-ping 'disable'
  - set firewall ipv6-src-route 'disable'
  - set firewall source-validation 'disable'
  - set firewall receive-redirects 'disable'
  - set firewall ipv6-receive-redirects 'disable'
  - set firewall twa-hazards-protection 'disable'
  - set firewall name OUTSIDE-IN default-action 'drop'
  - set firewall name OUTSIDE-IN rule 10 action 'accept'
  - set firewall name OUTSIDE-IN rule 10 state established 'enable'
  - set firewall name OUTSIDE-IN rule 10 state related 'enable'
  - set firewall name OUTSIDE-LOCAL default-action 'drop'
  - set firewall name OUTSIDE-LOCAL rule 10 action 'accept'
  - set firewall name OUTSIDE-LOCAL rule 10 state established 'enable'
  - set firewall name OUTSIDE-LOCAL rule 10 state related 'enable'
  - set firewall name OUTSIDE-LOCAL rule 20 action 'accept'
  - set firewall name PUBLIC-IN default-action 'drop'
  - set firewall name PUBLIC-IN rule 10 action 'accept'
  - set firewall name PUBLIC-IN rule 10 state established 'enable'
  - set firewall name PUBLIC-IN rule 10 state related 'enable'
  - set firewall name PUBLIC-LOCAL default-action 'drop'
  - set firewall name PUBLIC-LOCAL rule 10 action 'accept'
  - set firewall name PUBLIC-LOCAL rule 10 state established 'enable'
  - set firewall name PUBLIC-LOCAL rule 10 state related 'enable'
  - set firewall name PUBLIC-LOCAL rule 20 action 'accept'
  - set firewall name PUBLIC-LOCAL rule 20 icmp type-name 'echo-request'
  - set firewall name PUBLIC-LOCAL rule 20 protocol 'icmp'
  - set firewall name PUBLIC-LOCAL rule 20 state new 'enable'
  - set firewall name PUBLIC-LOCAL rule 30 action 'drop'
  - set firewall name PUBLIC-LOCAL rule 31 destination port '2222'
  - set firewall name PUBLIC-LOCAL rule 31 protocol 'tcp'
  - set firewall name PUBLIC-LOCAL rule 31 recent count '4'
  - set firewall name PUBLIC-LOCAL rule 31 recent time '60'
  - set firewall name PUBLIC-LOCAL rule 31 state new 'enable'
  - set firewall name PUBLIC-LOCAL rule 32 action 'accept'
  - set firewall name PUBLIC-LOCAL rule 32 destination port '2222'
  - set firewall name PUBLIC-LOCAL rule 32 protocol 'tcp'
  - set firewall name PUBLIC-LOCAL rule 32 state new 'enable'
  - set interfaces ethernet eth0 address 'dhcp'
  - set interfaces ethernet eth0 address 'dhcpv6'
  - set interfaces ethernet eth0 description 'PUBLIC'
  - set interfaces ethernet eth0 firewall in name 'PUBLIC-IN'
  - set interfaces ethernet eth0 firewall local name 'PUBLIC-LOCAL'
  - set interfaces ethernet eth1 address '192.168.16.1/24'
  - set interfaces ethernet eth1 description 'LAN'
  - set interfaces loopback lo
  - set nat source rule 100 outbound-interface 'eth0'
  - set nat source rule 100 translation address 'masquerade'
  - set protocols static route 0.0.0.0/0 next-hop 192.168.1.1
  - set service dns forwarding cache-size '1000'
  - set service dns forwarding allow-from '0.0.0.0/0'
  - set service dns forwarding listen-address '0.0.0.0'
  - set service dns forwarding name-server '192.168.1.1'
  - set service dns forwarding name-server '1.1.1.1'
  - set system name-server '127.0.0.1'
  - set service ssh client-keepalive-interval '180'
  - set service ssh listen-address '0.0.0.0'
  - set service ssh port '2222'
  - delete service ssh port '22'
  - set system config-management commit-revisions '100'
  - set system console device ttyS0 speed '9600'
  - set system host-name 'voyager'
  - set system domain-name 'kubespray.home.arpa'
  - set system login user {{ .Values.user.name }} authentication public-keys {{ .Values.user.name }} key '{{ .Values.user.credentials.sshpubkey | replace "ssh-rsa " "" }}'
  - set system login user {{ .Values.user.name }} authentication public-keys {{ .Values.user.name }}  type 'ssh-rsa'
  - set service ssh disable-password-authentication
  - set system ntp server 0.pool.ntp.org
  - set system ntp server 1.pool.ntp.org
  - set system ntp server 2.pool.ntp.org
  - set system syslog global facility all level 'notice'
  - set system syslog global facility protocols level 'debug'
  - set firewall name PUBLIC-IN rule 71 description 'Allow Port Forward public ssh port 22 to bastion 192.168.16.12 port 22'
  - set firewall name PUBLIC-IN rule 71 action 'accept'
  - set firewall name PUBLIC-IN rule 71 destination port '22'
  - set firewall name PUBLIC-IN rule 71 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 71 state new 'enable'
  - set firewall name PUBLIC-IN rule 72 action 'accept'
  - set firewall name PUBLIC-IN rule 72 destination port '22'
  - set firewall name PUBLIC-IN rule 72 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 72 state new 'enable'
  - set nat destination rule 70 description 'Port Forward public ssh port 22 to bastion 192.168.16.12 port 22'
  - set nat destination rule 70 inbound-interface 'eth0'
  - set nat destination rule 70 translation address '192.168.16.12'
  - set nat destination rule 70 destination port '22'
  - set nat destination rule 70 translation port '22'
  - set nat destination rule 70 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 81 description 'Allow TCP Port Forward public rdp port 3389 to bastion 192.168.16.12 port 3389'
  - set firewall name PUBLIC-IN rule 81 action 'accept'
  - set firewall name PUBLIC-IN rule 81 destination port '3389'
  - set firewall name PUBLIC-IN rule 81 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 81 state new 'enable'
  - set firewall name PUBLIC-IN rule 82 action 'accept'
  - set firewall name PUBLIC-IN rule 82 destination port '3389'
  - set firewall name PUBLIC-IN rule 82 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 82 state new 'enable'
  - set nat destination rule 80 description 'Port Forward public tcp rdp port 3389 to bastion 192.168.16.12 port 3389'
  - set nat destination rule 80 inbound-interface 'eth0'
  - set nat destination rule 80 translation address '192.168.16.12'
  - set nat destination rule 80 destination port '3389'
  - set nat destination rule 80 translation port '3389'
  - set nat destination rule 80 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 91 description 'Allow UDP Port Forward public rdp port 3389 to bastion 192.168.16.12 port 3389'
  - set firewall name PUBLIC-IN rule 91 action 'accept'
  - set firewall name PUBLIC-IN rule 91 destination port '3389'
  - set firewall name PUBLIC-IN rule 91 protocol 'udp'
  - set firewall name PUBLIC-IN rule 91 state new 'enable'
  - set firewall name PUBLIC-IN rule 92 action 'accept'
  - set firewall name PUBLIC-IN rule 92 destination port '3389'
  - set firewall name PUBLIC-IN rule 92 protocol 'udp'
  - set firewall name PUBLIC-IN rule 92 state new 'enable'
  - set nat destination rule 90 description 'Port Forward public udp rdp port 3389 to bastion 192.168.16.12 port 3389'
  - set nat destination rule 90 inbound-interface 'eth0'
  - set nat destination rule 90 translation address '192.168.16.12'
  - set nat destination rule 90 destination port '3389'
  - set nat destination rule 90 translation port '3389'
  - set nat destination rule 90 protocol 'udp'
  - set system static-host-mapping host-name node1 inet '192.168.16.61'
  - set system static-host-mapping host-name node2 inet '192.168.16.62'
  - set system static-host-mapping host-name node3 inet '192.168.16.63'
  - set system static-host-mapping host-name node1 inet '192.168.16.61'
  - set system static-host-mapping host-name node2 inet '192.168.16.62'
  - set system static-host-mapping host-name node3 inet '192.168.16.63'
  - set system static-host-mapping host-name argocd.home.arpa inet '192.168.16.66'
  - set system static-host-mapping host-name kubespray.home.arpa inet '192.168.16.60'
  - set system static-host-mapping host-name grpc.argocd.home.arpa inet '192.168.16.66'
  - set system static-host-mapping host-name api.kubespray.home.arpa inet '192.168.16.60'
  - set system static-host-mapping host-name node1.kubespray.home.arpa inet '192.168.16.61'
  - set system static-host-mapping host-name node2.kubespray.home.arpa inet '192.168.16.62'
  - set system static-host-mapping host-name node3.kubespray.home.arpa inet '192.168.16.63'
  - set firewall name PUBLIC-IN rule 38 description 'Allow TCP Port Forward public HTTPS port 443 to LoadBalancer VIP 192.168.16.60 port 443'
  - set firewall name PUBLIC-IN rule 38 action 'accept'
  - set firewall name PUBLIC-IN rule 38 destination port '80'
  - set firewall name PUBLIC-IN rule 38 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 38 state new 'enable'
  - set firewall name PUBLIC-IN rule 39 action 'accept'
  - set firewall name PUBLIC-IN rule 39 destination port '80'
  - set firewall name PUBLIC-IN rule 39 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 39 state new 'enable'
  - set nat destination rule 37 description 'Allow TCP Port Forward public HTTPS port 443 to LoadBalancer VIP 192.168.16.60 port 443'
  - set nat destination rule 37 inbound-interface 'eth0'
  - set nat destination rule 37 translation address '192.168.16.60'
  - set nat destination rule 37 destination port '80'
  - set nat destination rule 37 translation port '80'
  - set nat destination rule 37 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 41 description 'Allow TCP Port Forward public HTTPS port 443 to LoadBalancer VIP 192.168.16.60 port 443'
  - set firewall name PUBLIC-IN rule 41 action 'accept'
  - set firewall name PUBLIC-IN rule 41 destination port '443'
  - set firewall name PUBLIC-IN rule 41 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 41 state new 'enable'
  - set firewall name PUBLIC-IN rule 42 action 'accept'
  - set firewall name PUBLIC-IN rule 42 destination port '443'
  - set firewall name PUBLIC-IN rule 42 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 42 state new 'enable'
  - set nat destination rule 40 description 'Allow TCP Port Forward public HTTPS port 443 to LoadBalancer VIP 192.168.16.60 port 443'
  - set nat destination rule 40 inbound-interface 'eth0'
  - set nat destination rule 40 translation address '192.168.16.60'
  - set nat destination rule 40 destination port '443'
  - set nat destination rule 40 translation port '443'
  - set nat destination rule 40 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 43 description 'Allow TCP Port Forward public kubespray api port 8443 to LoadBalancer VIP 192.168.16.60'
  - set firewall name PUBLIC-IN rule 43 action 'accept'
  - set firewall name PUBLIC-IN rule 43 destination port '8443'
  - set firewall name PUBLIC-IN rule 43 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 43 state new 'enable'
  - set firewall name PUBLIC-IN rule 44 action 'accept'
  - set firewall name PUBLIC-IN rule 44 destination port '8443'
  - set firewall name PUBLIC-IN rule 44 protocol 'tcp'
  - set firewall name PUBLIC-IN rule 44 state new 'enable'
  - set nat destination rule 45 description 'Allow TCP Port Forward public kubespray api port 8443 to LoadBalancer VIP 192.168.16.60'
  - set nat destination rule 45 inbound-interface 'eth0'
  - set nat destination rule 45 translation address '192.168.16.60'
  - set nat destination rule 45 destination port '8443'
  - set nat destination rule 45 translation port '8443'
  - set nat destination rule 45 protocol 'tcp'
  - commit
  - save
